In [21]:
import pandas as pd
import numpy as np

In [22]:
df=pd.read_csv('ecom.csv')
df.head()

,Date,ProductName,ProductCategory,ProductSubCategory,ProductPrice,CustomerName,CustomerEmail,CustomerAddress,CustomerPhone,CustomerSegment,...,SupplierContact,ShipperName,ShippingMethod,QuantitySold,TotalAmount,DiscountAmount,NetAmount,StockReceived,StockSold,StockOnHand
0,2023-09-14,Nathaniel,Electronics,Camera,0.01,Colleen Kelly,maryhurst@example.org,"354 Mcdowell Turnpike, Port Charles, CT 95318",908.610.2711x8507,Silver,...,6538306661,and Sons,Ground,49,31965.15,121.07,31844.08,475,127,348
1,2023-02-11,NonExistentProduct,Electronics,Mobile,847.43,Joel Wright,sandersvictoria@example.org,"24740 Fox Villages, New Tracie, MA 53038",+1-408-938-0389x952,Gold,...,NaN,PLC,Air,73,61862.39,91.09,61771.30,487,243,244
2,2021-11-12,Angela,InvalidCategory,Action Figures,386.57,Thomas Sawyer,ospence@example.net,"769 Joe Trail, East Terri, CA 43813",001-929-516-1919x39288,Gold,...,+1-588-750-7646,PLC,Sea,89,34404.73,10.56,34394.17,341,188,153
3,11-15-2021,Amy,Home & Garden,Decor,364.01,Tyler Gardner,christopherjohnson@example.com,"27783 Olivia Centers, Williamsmouth, AL 09809",8907712983,Gold,...,805-650-6257x5876,LLC,Air,3,1092.03,69.06,1022.97,500,124,376
4,2023-04-22,Nathaniel,Electronics,Camera,652.35,Meagan Peterson,epowell@example.net,"25357 Blackwell Locks, Andreabury, MH 27857",9999921886,Gold,...,6538306661,Ltd,Sea,75,48926.25,137.17,48789.08,429,351,78

In [23]:
# Shuffle the data
df_shuffled = df.sample(frac=1, random_state=42)


#input db_percentage et json_percentage
json_percentage = float(input('Enter json percentage from 0 to 1: '))

# Calculate the number of rows for each destination
total_rows = df_shuffled.shape[0]
json_rows = int(json_percentage * total_rows)
csv_rows = total_rows - json_rows

# Split the data into JSON and CSV parts
df_json = df_shuffled.iloc[:json_rows]
df_csv = df_shuffled.iloc[json_rows:]

In [24]:
# Save the splits to their respective destinations (JSON, database, and CSV)
df_json.to_json('ecommerce.json', orient='records')
df_csv.to_csv('ecommerce.csv', index=False)